SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 900
FOV= 1500
DISTANCE = 1000
LINE_WIDTH = 1

ROWS = 8 # front back           Z
LEVEL = 8 # up - down           Y
COLUMNS = 8 # left - right      X

SIZE = 15
Y_SPACING = 0
BOX_SPACING = 5
NO_VISIBILITY = False
#BOX_SPACING = 10

DEBUG = False
TEAM_BLACK = 0
TEAM_WHITE = 1